### PR TITLE
refactor: make config script deterministic for building c library, fixes

### PR DESCRIPTION
**Pull request by kittywhiskers**
The current behavior of Miracl Core's `config*.py` for C are as follows

* It crashes when a non-integer input is given
* Each run of the script modifies the source tree in a way that is disruptive, forcing the user to run `git reset --hard` just to be able to run the script a second time
* The script litters the source tree with files that are generated ethereally, deleting source files instead
* Unlike every other curve, the Million Dollar Curve is referred to as MDC, Million Dollar Curve inconsistently and not by its technical name
* The script has an extreme reliance on the system shell to perform most operations, including trivial file deletion and copying
* The usage of `gcc` is presumed and the script needs manual modification if you choose to use `clang`, if both are installed, the script will still default to the slower `gcc`
* The compiler will try to invoke `gcc` anyway even if it isn't installed

These behaviors and some additional refactoring (moving globals and comments to more appropriate places) have been done, instead of one giant commit, changes have been done in steps to make reviewing easier, even if the next commit eventually neutralizes the changes done previously

### CODE REVIEW

**Comment by mcarrickscott** [comment]
Thanks! What about swift/config64.py...

**Comment by mcarrickscott** [comment]
Thanks! What about swift/config64.py?

**Comment by kittywhiskers** [comment]
Don't really work with Swift so never looked into it, depending on this PR's response I was gonna make another one but for C++, I'll give Swift a look

**Comment by mcarrickscott** [comment]
Had to make a few changes. When all generated files are deleted, so were
the headers! They are needed to compile test programs.

If testing, programs again run immediately (to be compatible with
documentation and other languages)

Renamed Million Dollar Curve to simply MDC, as that is the name used in ROM
files.

Your contribution flushed out a few other bugs, so thanks again.

Mike

**Pull request merged**
