### PR TITLE
Add Travis CI configuration

### PR DESCRIPTION
**Pull request by todinov**

### CODE REVIEW

**Comment by mcarrickscott** [comment]
Hello Ivan,

I merged your pull request... but I'm not really sure what I am doing, or
what you want me to do?

What should I expect to happen?

Mike

**Comment by todinov** [comment]
Hi Mike,
Now that you've merged it, the CI is running on the master branch. You can see it in travis https://travis-ci.org/miracl/core, and soon the badge in the readme should be green.

**Comment by mcarrickscott** [comment]
So it is!

Note that for most languages you can now do for example

python3 config64.py test

and this will automatically build and run all of the test programs...

Mike

**Comment by todinov** [comment]
Yes, this is exactly what we are executing in Travis. With a bit of additional work, we can also execute the tests for 32-bit too, but I'm not sure if there is a need for that.

**Pull request merged**
